tracer.property: "I AM THE DEFAULT"
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password: 123Ui*
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  redis:
#    prot: 6379
#    host: 127.0.0.1
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 8
#        max-wait: 1000
#        shutdown-timeout: 100
#
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
signing.key: "345345fsdfsf5345"
